"""Generate per-site OpenResty server blocks and trigger an engine reload.

Site topology (domain / listen / origin) lives in nginx config files, so adding
or changing a site requires regenerating conf.d and reloading nginx. Rule/list
changes do NOT need this (they hot-sync via Redis).
"""
from __future__ import annotations

import asyncio
import logging
import os
import subprocess

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core.config import settings
from app.core.redis import get_redis
from app.models import Site
from app.services.origin import build_upstream_url

log = logging.getLogger("waf.nginx_conf")

RELOAD_KEY = "waf:nginx:reload"
ENGINE_NGINX_CONF = "/usr/local/openresty/nginx/conf/nginx.conf"
ENGINE_RELOAD_CMD = (
    "/usr/local/openresty/bin/openresty",
    "-s",
    "reload",
    "-c",
    ENGINE_NGINX_CONF,
)

_FOLLOW_TEMPLATE = """# generated by WAF backend - do not edit manually
map $scheme $waf_upstream_{site_id} {{
    default {upstream_http};
    https   {upstream_https};
}}

server {{
{listen_lines}    server_name {domain};
    set $waf_site_id "{site_id}";

    include /etc/nginx/snippets/waf.conf;
{ssl_block}
    location / {{
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass $waf_upstream_{site_id};
    }}
}}
"""

_FIXED_TEMPLATE = """# generated by WAF backend - do not edit manually
server {{
{listen_lines}    server_name {domain};
    set $waf_site_id "{site_id}";

    include /etc/nginx/snippets/waf.conf;
{ssl_block}
    location / {{
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass {upstream};
    }}
}}
"""


def _resolve_ssl_paths(site: Site) -> tuple[str | None, str | None]:
    if site.certificate_id and site.certificate:
        return site.certificate.cert_path, site.certificate.key_path
    return None, None


def _build_listen_lines(site: Site, has_ssl: bool) -> str:
    lines: list[str] = []
    if site.listen_http:
        lines.append("    listen 80;")
    if site.listen_https and has_ssl:
        lines.append("    listen 443 ssl;")
    elif site.listen_https:
        log.warning(
            "site %s (id=%s): listen_https=true but ssl cert/key missing, skip 443",
            site.domain,
            site.id,
        )
    return "\n".join(lines) + ("\n" if lines else "")


def render_site(site: Site) -> str:
    cert_path, key_path = _resolve_ssl_paths(site)
    has_ssl = bool(cert_path and key_path)
    listen_lines = _build_listen_lines(site, has_ssl)
    if not listen_lines.strip():
        log.warning(
            "site %s (id=%s): no listen ports configured, skip conf generation",
            site.domain,
            site.id,
        )
        return ""

    ssl_block = ""
    if site.listen_https and has_ssl:
        ssl_block = (
            f"    ssl_certificate {cert_path};\n"
            f"    ssl_certificate_key {key_path};\n"
        )

    upstream_http = build_upstream_url(
        site.origin_host, "http", site.origin_http_port
    )
    upstream_https = build_upstream_url(
        site.origin_host, "https", site.origin_https_port
    )

    if site.origin_protocol == "follow":
        return _FOLLOW_TEMPLATE.format(
            site_id=site.id,
            domain=site.domain,
            listen_lines=listen_lines,
            ssl_block=ssl_block,
            upstream_http=upstream_http,
            upstream_https=upstream_https,
        )

    if site.origin_protocol == "http":
        upstream = upstream_http
    else:
        upstream = upstream_https

    return _FIXED_TEMPLATE.format(
        site_id=site.id,
        domain=site.domain,
        listen_lines=listen_lines,
        ssl_block=ssl_block,
        upstream=upstream,
    )


async def regenerate(db: AsyncSession) -> None:
    """Rewrite conf.d for all enabled sites, drop stale files, trigger reload."""
    conf_dir = settings.engine_conf_dir
    os.makedirs(conf_dir, exist_ok=True)

    sites = (
        await db.execute(
            select(Site).options(selectinload(Site.certificate))
        )
    ).scalars().all()
    wanted = {}
    for s in sites:
        if s.enabled:
            content = render_site(s)
            if content:
                wanted[f"site_{s.id}.conf"] = content

    # write wanted files
    for fname, content in wanted.items():
        path = os.path.join(conf_dir, fname)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

    # remove stale generated files
    for fname in os.listdir(conf_dir):
        if fname.startswith("site_") and fname.endswith(".conf") and fname not in wanted:
            try:
                os.remove(os.path.join(conf_dir, fname))
            except OSError:
                pass

    await trigger_reload()
    log.info("regenerated %d site confs", len(wanted))


def _reload_engine_sync() -> None:
    """Reload OpenResty as the backend process (root); Lua workers cannot."""
    try:
        subprocess.run(
            ENGINE_RELOAD_CMD,
            check=True,
            capture_output=True,
            text=True,
            timeout=15,
        )
        log.info("engine nginx reload OK")
    except subprocess.CalledProcessError as exc:
        log.error(
            "engine nginx reload failed (exit %s): %s",
            exc.returncode,
            (exc.stderr or exc.stdout or "").strip(),
        )
        raise
    except OSError as exc:
        log.error("engine nginx reload failed: %s", exc)
        raise


async def trigger_reload() -> None:
    """Bump reload version and reload OpenResty so conf.d changes take effect."""
    await get_redis().incr(RELOAD_KEY)
    await asyncio.to_thread(_reload_engine_sync)
